### ISSUE TITLE
curl is ok 

### ISSUE THREAD

**Issue by pythonohtyp** [anapsix/feron#1]
curl return is correct.

**Comment by anapsix** [comment]
please provide some context / details about the environment where it's running and version of feron you're using

**Comment by anapsix** [comment]
I was able to replicate the issue by running it on Fedora 32.
```
Unhandled exception: SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed (OpenSSL::SSL::Error)
```
Looks like, statically compiled in Alpine Linux binary doesn't work well in non-alpine env.
I suggest using feron's docker image: [anapsix/feron](https://hub.docker.com/repository/docker/anapsix/feron), since it's based on Alpine. Or building a binary on OS which will be used as target running environment.
